Fix: update editorPageView render to try/catch consistent with editorDataLoader (fixes #271)
adapt-security/adapt-authoring-ui pull request #272
Opened 2023-12-14 12:00 UTC by joe-allen-89

[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Add a link to the original issue)
#271 

[//]: # (Delete as appropriate)
### Fix
* Update editorPageView render to try/catch consistent with editorDataLoader (#271)

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Steps for testing

[//]: # (Mention any other dependencies)

2023-12-18 10:58 UTC, taylortom requested changes

2023-12-18 10:58 UTC, taylortom commented on app/modules/editor/contentObject/views/editorPageView.js
> +        ]);
We don't need the `Promise.all` here, as we're just doing one fetch:

```suggestion
        await Origin.editor.data.content.fetch();
```

Otherwise, looks good :)

2023-12-18 11:28 UTC, chris-steele approved these changes

2024-01-02 17:00 UTC, taylortom approved these changes

2024-01-02 17:00 UTC, merged